-- Files a pasted Copilot/Teams meeting summary into the site's `meetings/`
-- folder and replaces the selection with a link to it.
--
-- Select the pasted summary in a Markdown buffer and run
-- `:FileMeetingAiSummary`.

local M = {}

local WEEKDAYS = { 'Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat' }
local DEFAULT_AI_LINE = '_Generated by AI. Make sure to check for accuracy._'

local function trim(s)
    return (s:gsub('^%s+', ''):gsub('%s+$', ''))
end

local function indent_of(line)
    return #line:match('^%s*')
end

local function strip_quote(line)
    return (line:gsub('^%s*>%s?', ''))
end

local function strip_bullet_marker(s)
    return (s:gsub('^[-*+]%s+', ''))
end

-- Tolerates `Meeting notes:`, `## Meeting notes`, `- Meeting notes:`,
-- `**Meeting notes**:` etc.
local function heading_kind(line)
    local t = trim(line):gsub('^#+%s*', ''):gsub('^[-*+]%s+', ''):gsub('[%*_]', '')
    t = trim(t):gsub(':$', ''):lower()
    if t == 'meeting notes' then
        return 'notes'
    elseif t == 'follow-up tasks' or t == 'follow up tasks' or t == 'followup tasks' then
        return 'tasks'
    end
end

local function dedent(lines)
    local min
    for _, l in ipairs(lines) do
        if l:match('%S') then
            local i = indent_of(l)
            if not min or i < min then
                min = i
            end
        end
    end
    min = min or 0
    local out = {}
    for _, l in ipairs(lines) do
        out[#out + 1] = l:match('%S') and l:sub(min + 1) or ''
    end
    return out
end

-- Items are { depth, text }. Hard-wrapped continuation lines are folded into
-- the preceding item; each distinct indent counts as one nesting level.
local function parse_bullets(lines)
    local items, levels = {}, {}
    for _, l in ipairs(dedent(lines)) do
        if l:match('^%s*[-*+]%s+') then
            local ind = indent_of(l)
            while #levels > 0 and levels[#levels] > ind do
                table.remove(levels)
            end
            if #levels == 0 or levels[#levels] < ind then
                levels[#levels + 1] = ind
            end
            items[#items + 1] = { depth = #levels - 1, text = trim(strip_bullet_marker(trim(l))) }
        elseif l:match('%S') then
            if #items > 0 then
                items[#items].text = items[#items].text .. ' ' .. trim(l)
            else
                items[#items + 1] = { depth = 0, text = trim(l) }
            end
        end
    end
    return items
end

local function render_notes(items)
    local out = {}
    for _, it in ipairs(items) do
        if it.depth == 0 and #out > 0 then
            out[#out + 1] = ''
        end
        out[#out + 1] = string.rep('  ', it.depth) .. '- ' .. it.text
    end
    return out
end

-- Groups actions by owner: a trailing `(Owner)` on each action, or
-- pre-grouped `Owner:` lines.
local function render_tasks(lines)
    local groups, order, items, current = {}, {}, {}, nil
    local after_blank = true

    for _, l in ipairs(dedent(lines)) do
        local t = trim(l)
        local is_bullet = t:match('^[-*+]%s+') ~= nil
        local header = not is_bullet and t:match('^[%*_]*([^:]-)[%*_]*:[%*_]*$')
        if t == '' then
            after_blank = true
        elseif header and trim(header) ~= '' then
            current = trim(header)
            after_blank = false
        elseif is_bullet then
            items[#items + 1] = { owner = current, text = trim(strip_bullet_marker(t)) }
            after_blank = false
        elseif #items > 0 and not after_blank and not t:match('^%*%*') then
            -- hard-wrapped continuation of the previous item
            items[#items].text = items[#items].text .. ' ' .. t
        else
            -- Teams emits unbulleted, blank-line-separated paragraphs
            items[#items + 1] = { owner = current, text = t }
            after_blank = false
        end
    end

    for _, it in ipairs(items) do
        local text, owner = it.text, it.owner
        local body, who = text:match('^(.-)%s*%(([^()]+)%)%s*$')
        if body then
            text, owner = body, trim(who)
        end
        owner = owner or 'Unassigned'
        if not groups[owner] then
            groups[owner] = {}
            order[#order + 1] = owner
        end
        table.insert(groups[owner], text)
    end

    local out = {}
    for _, owner in ipairs(order) do
        if #out > 0 then
            out[#out + 1] = ''
        end
        out[#out + 1] = '### ' .. owner
        for _, text in ipairs(groups[owner]) do
            out[#out + 1] = ''
            out[#out + 1] = '- ' .. text
        end
    end
    return out
end

--- Reformats raw summary lines into the meeting page body (without the H1).
--- Returns lines, or nil plus an error message.
function M.reformat(raw)
    local ai_line, notes, tasks, section = nil, {}, {}, nil
    for _, l in ipairs(raw) do
        l = strip_quote(l)
        local kind = heading_kind(l)
        if kind then
            section = kind
        elseif trim(l):lower():find('generated by ai', 1, true) then
            ai_line = ai_line or trim(l)
        elseif section == 'notes' then
            notes[#notes + 1] = l
        elseif section == 'tasks' then
            tasks[#tasks + 1] = l
        end
    end

    if #notes == 0 and #tasks == 0 then
        return nil, "Selection has no 'Meeting notes' / 'Follow-up tasks' sections"
    end

    local out = { ai_line or DEFAULT_AI_LINE, '' }
    if #notes > 0 then
        vim.list_extend(out, { '## Meeting Notes', '' })
        vim.list_extend(out, render_notes(parse_bullets(notes)))
        out[#out + 1] = ''
    end
    if #tasks > 0 then
        vim.list_extend(out, { '## Follow-up Tasks', '' })
        vim.list_extend(out, render_tasks(tasks))
        out[#out + 1] = ''
    end
    return out
end

--- Parses YYYY-MM-DD, DD/MM/YYYY or DD/MM (current year). Returns
--- "YYYY-MM-DD", "Ddd" or nil.
function M.parse_date(s)
    s = trim(s or '')
    local y, m, d = s:match('^(%d%d%d%d)-(%d%d?)-(%d%d?)$')
    if not y then
        d, m, y = s:match('^(%d%d?)/(%d%d?)/(%d%d%d%d)$')
    end
    if not y then
        d, m = s:match('^(%d%d?)/(%d%d?)$')
        y = d and os.date('%Y')
    end
    if not y then
        return nil
    end
    y, m, d = tonumber(y), tonumber(m), tonumber(d)
    local t = os.time({ year = y, month = m, day = d, hour = 12 })
    local parts = os.date('*t', t)
    -- os.time normalises invalid dates (e.g. 31 Feb); reject those.
    if parts.day ~= d or parts.month ~= m then
        return nil
    end
    return os.date('%Y-%m-%d', t), WEEKDAYS[parts.wday]
end

--- Nearest `meetings` directory in `start` or any ancestor.
function M.find_meetings_dir(start)
    return vim.fs.find('meetings', { path = start, upward = true, type = 'directory' })[1]
end

--- Relative path from directory `from` to file `to` (both absolute).
function M.relpath(from, to)
    local f, t = vim.split(from, '/', { plain = true }), vim.split(to, '/', { plain = true })
    local i = 1
    while i <= #f and i < #t and f[i] == t[i] do
        i = i + 1
    end
    local parts = {}
    for _ = i, #f do
        parts[#parts + 1] = '..'
    end
    for j = i, #t do
        parts[#parts + 1] = t[j]
    end
    return table.concat(parts, '/')
end

function M.encode_path(path)
    return (path:gsub('[ :,#%%%?]', function(c)
        return string.format('%%%02X', c:byte())
    end))
end

local function file_meeting(line1, line2)
    local buf = vim.api.nvim_get_current_buf()
    local src = vim.api.nvim_buf_get_name(buf)
    if src == '' then
        return vim.notify('FileMeetingAiSummary: buffer has no file name', vim.log.levels.ERROR)
    end
    local src_dir = vim.fs.dirname(vim.fn.fnamemodify(src, ':p'))
    local meetings = M.find_meetings_dir(src_dir)
    if not meetings then
        return vim.notify('FileMeetingAiSummary: no `meetings/` folder found above ' .. src_dir, vim.log.levels.ERROR)
    end

    local raw = vim.api.nvim_buf_get_lines(buf, line1 - 1, line2, false)
    local body, err = M.reformat(raw)
    if not body then
        return vim.notify('FileMeetingAiSummary: ' .. err, vim.log.levels.ERROR)
    end
    local indent = raw[1]:match('^%s*') or ''

    vim.ui.input({ prompt = 'Meeting date (YYYY-MM-DD or DD/MM): ', default = os.date('%Y-%m-%d') }, function(date_in)
        if not date_in then
            return
        end
        local date, dow = M.parse_date(date_in)
        if not date then
            return vim.notify("FileMeetingAiSummary: invalid date '" .. date_in .. "'", vim.log.levels.ERROR)
        end
        vim.ui.input({ prompt = 'Meeting title: ' }, function(title)
            title = trim((title or ''):gsub('[/\\]', '-'))
            if title == '' then
                return
            end
            local name = string.format('%s %s: %s', date, dow, title)
            local target = meetings .. '/' .. name .. '.md'
            if vim.uv.fs_stat(target) then
                return vim.notify('FileMeetingAiSummary: already exists: ' .. target, vim.log.levels.ERROR)
            end

            local content = { '# ' .. name, '' }
            vim.list_extend(content, body)
            if vim.fn.writefile(content, target) ~= 0 then
                return vim.notify('FileMeetingAiSummary: failed to write ' .. target, vim.log.levels.ERROR)
            end

            local rel = M.encode_path(M.relpath(src_dir, target))
            local link = string.format('%sSee AI summary under "Meetings": [%s.md](%s)', indent, name, rel)
            vim.api.nvim_buf_set_lines(buf, line1 - 1, line2, false, { link })
            vim.notify('Filed ' .. name .. '.md')
        end)
    end)
end

function M.setup()
    vim.api.nvim_buf_create_user_command(0, 'FileMeetingAiSummary', function(opts)
        if opts.range == 0 then
            return vim.notify(
                'FileMeetingAiSummary: select the meeting summary in Visual mode first',
                vim.log.levels.ERROR
            )
        end
        file_meeting(opts.line1, opts.line2)
    end, {
        range = true,
        force = true,
        desc = 'File selected AI meeting summary under meetings/ and link it',
    })
    return M
end

return M
